#directions
RIGHT = [1,0]
UP = [0,1]
LEFT = [-1,0]
DOWN = [0,-1]

#direction list
DIR_LIST = [RIGHT, UP, LEFT, DOWN]
#modes
LEVEL = True
BATTLE = False

TILES_WIDE = 20
TILES_TALL = 15
TILE_SCALE = 32
SCREEN_WIDTH = TILE_SCALE*TILES_WIDE
SCREEN_HEIGHT = TILE_SCALE*TILES_TALL

END = 1 
WIN = 0
IN_PROG = -1

ANIMAL_TYPES = ['bird', 'pig', 'seal']
