#directions
RIGHT = 0
UP = 1
LEFT = 2
DOWN = 3
#modes
LEVEL = True
BATTLE = False

SCREEN_WIDTH = 640
SCREEN_HEIGHT = 480
TILE_SCALE = 32
TILES_WIDE = SCREEN_WIDTH/TILE_SCALE
TILES_TALL = SCREEN_HEIGHT/TILE_SCALE
