#directions
RIGHT = [1,0]
UP = [0,1]
LEFT = [-1,0]
DOWN = [0,-1]

#direction list
DIR_LIST = [RIGHT, UP, LEFT, DOWN]

#modes
LEVEL = True
BATTLE = False

SCREEN_WIDTH = 640
SCREEN_HEIGHT = 480
TILE_SCALE = 32
TILES_WIDE = SCREEN_WIDTH/TILE_SCALE
TILES_TALL = SCREEN_HEIGHT/TILE_SCALE

END = 1 
WIN = 0
IN_PROG = -1

ANIMAL_TYPES = ['bird', 'pig', 'seal']

FAT_DECREASE_RATE = 8